version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      test-dependencies:
        patterns: ["*"]
        exclude-patterns:
          # These versions are pinned by pytest-homeassistant-custom-component
          # and must move together with that package.
          - coverage
          - pytest
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
